apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  data:
  - secretKey: api-key
    remoteRef:
      key: "df411000-6237-40d9-ba4b-b37e01227a72"