provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/kashalls/external-dns-unifi-webhook
      tag: v0.6.0
    env:
      - name: UNIFI_HOST
        value: https://192.168.50.1 # replace with the address to your UniFi router/controller
      - name: UNIFI_EXTERNAL_CONTROLLER
        value: "false"
      - name: UNIFI_SITE
        value: "default"
      - name: UNIFI_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-unifi-secret
            key: api-key
      - name: LOG_LEVEL
        value: info
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
extraArgs:
- --ignore-ingress-tls-spec
policy: upsert-only
sources: ["ingress", "service"] # or whatever you need
registry: noop
domainFilters: ["pi.home.notasecret.net", "home.notasecret.net"]