apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
- namespace.yaml

helmCharts:
  - name: home-assistant
    repo: https://pajikos.github.io/home-assistant-helm-chart/
    version: 0.3.26
    releaseName: home-assistant
    namespace: home-assistant
    valuesFile: values.yaml