replicaCount: 1
persistence:
  enabled: true
  storageClass: longhorn
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  className: "nginx"
  hosts:
    - host: ha.home.notasecret.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: home-assistant-tls
      hosts:
        - ha.home.notasecret.net
configuration:
  enabled: true
  trusted_proxies:
    - 10.0.0.0/8
# initContainers:
#   - name: init-hacs
#     image: bash
#     command: ["bash", "-c", "cd /config && wget -O - https://get.hacs.xyz | bash -"]
#     volumeMounts:
#       - mountPath: /config
#         name: home-assistant
