apiVersion: v2
name: argo-cd
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 9.0.1
    alias: argo-cd