apiVersion: v2
name: cert-manager
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.17.2
    alias: cert-manager