apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd
  name: applications
  labels:
    app.kubernetes.io/part-of: applications
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  generators:
    - git:
        repoURL: https://github.com/jslancaster/home-lab.git
        revision: main
        directories:
          - path: gitops/applications/*
  template:
    metadata:
      name: 'app-{{ path.basename }}'
      namespace: argocd
      labels:
        app.kubernetes.io/component: 'user-applications'
        app.kubernetes.io/part-of: applications
    spec:
      project: applications
      source:
        repoURL: https://github.com/jslancaster/home-lab.git
        targetRevision: main
        path: '{{ path }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: applications
        server: https://kubernetes.default.svc
      ignoreDifferences:
        - group: 'external-secrets.io'
          kind: 'ExternalSecret'
          jqPathExpressions:
            - '.spec.data[].remoteRef.conversionStrategy'
            - '.spec.data[].remoteRef.decodingStrategy'
            - '.spec.data[].remoteRef.metadataPolicy'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true