---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: external-dns
spec:
  encryptedData:
    password: AgARNeH+Pe+pHWudywW4IVvnTNS8SLp6Mb8brR8QBHQxZ1Ki0pL/OTWSEOtzsFF6IoQOjWrdpmShst7PNZoIg/dS8+P5HE8AzrbYCOAP+NGHV9RlD2MHQi6YZFbez+odkwQbj+lVqPq11qBCSef2cKny6EY5ow4DHxkGuSIKBLb8q712DmUAGWSVS/kU2lkXM9KzUv64VJtzq/mhAh00Jh8wuXZwpMa/BeJ4TzVqiUjWzFfM+6/TiznFaKgnEcIxGE6zLnGCeTnVnYHZJCTFdWQid0yaYGvTB/QB7ufbycTUt7RiITfufz14aNCreMb6oMOZtpZRZZ41UhvuzuXRJiL1jp6TmZ/xMkYBSg03WgNgzUhx4L66eG+Izgp4cH+EyhuxMJPANqNeWzOBOXIsCAouMNCB149P6jtkFQ1sZfbLGE2i3N+vMGC3FxYpPj8rZ2ou/46JEK+QEGGWJnPxlfHhL7zWKAUBfz4UdI+LFenOqgHKRIIir2f/dqxFameM66Ge1bjrBe2uUrxrSGUPsNZnIhql0/v5wWS1AlzrfOFfd4jRuHLhI+krp1ZLP0Fze3X9Kon3R5LNY95rvyf3wxv9YU4TTBXaBddIxxkS0v3A3mNFuEhMImStqArRQlm8WIS8UsY2SCgryl4I5LrXyiANe+UFpkR1iHfxleAjk+SR4HzvulEjzsmQXWYiEgTfgx+rmOW2j/0D6XE=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: external-dns
