apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-app
  namespace: netbox
spec:
  refreshInterval: "1h" # How often to check for changes
  secretStoreRef:
    name: kubernetes-store # A SecretStore that points to the Kubernetes API itself
    kind: ClusterSecretStore # Use a ClusterSecretStore to read across namespaces
  target:
    name: netbox-app # Name of the secret to be created in app-namespace
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: / 
        /cnpg-system/netbox-app