global:
  domain: argocd.pi.home.notasecret.net

configs:
  params:
    server.insecure: true
  cm:
    create: true
    kustomize.buildOptions: '--enable-helm'
redis-ha:
  enabled: true
controller:
  replicas: 1
server:
  replicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    extraTls:
      - hosts:
        - argocd.pi.home.notasecret.net
        secretName: argo-server-tls
repoServer:
  replicas: 2
applicationSet:
  replicas: 2