configs:
  cm:
    create: true
    kustomize.buildOptions: '--enable-helm'
redis-ha:
  enabled: true
controller:
  replicas: 1
server:
  replicas: 2
repoServer:
  replicas: 2
applicationSet:
  replicas: 2