apiVersion: v2
name: external-dns
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: 1.16.1
    alias: external-dns