apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- namespace.yaml
- bitwarden-sdk-server-cert.yaml
- bitwarden-store.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.20.3
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: values.yaml