---
k3s_cluster:
  children:
    server:
      hosts:
        kube-control-001.pi.home.notasecret.net:
    agent:
      hosts:
        kube-agent-001.pi.home.notasecret.net:
        kube-agent-002.pi.home.notasecret.net:
        kube-agent-003.pi.home.notasecret.net:
  
  vars:
    ansible_port: 22
    ansible_user: jeff
    k3s_version: v1.33.5+k3s1
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"

    # Optional Stuff
    extra_server_args: '--disable=traefik --disable=servicelb --tls-san="kube.pi.home.notasecret.net,192.168.50.100"'
    # extra_manifests: [
    #   '../../manifests/kube-vip/kube-vip-rbac.yaml',
    #   '../../manifests/kube-vip/kube-vip.yaml',
    #   '../../manifests/kube-vip/kube-vip-cloud-controller.yaml',
    #   '../../manifests/kube-vip/kube-vip-cloud-controller-config.yaml',
    # ]
    user_kubectl: false
    