apiVersion: v2
name: ingress-nginx
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.12.2
namespace: ingress-nginx