apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevip
  namespace: kube-system
data:
  range-global: 192.168.50.90-192.168.50.99                       # CIDR-based range which can be used in any Namespace
