apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-svc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  data:
  - secretKey: access-key
    remoteRef:
      key: "e408d800-b481-414b-a17c-b37e00ced9e5"
  - secretKey: secret-key
    remoteRef:
      key: "9b17be76-8f9e-4375-a1c4-b37e00cef1d2"