apiVersion: v2
name: grafana
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 9.2.10
    alias: grafana