pi-hole:
  admin:
    existingSecret: pi-hole-admin-password
  # ingress:
  #   enabled: true
  #   hosts:
  #     - pi-hole.pi.home.notasecret.net
  #   tls:
  #     - secretName: pi-hole-tls
  #       hosts:
  #         - pi-hole.pi.home.notasecret.net
  #   annotations:
  #     cert-manager.io/cluster-issuer: letsencrypt-prod
  #     external-dns.alpha.kubernetes.io/hostname: pi-hole.pi.home.notasecret.net
  persistentVolumeClaim:
    enabled: false
  replicaCount: 3
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  podDnsConfig:
    enabled: false
  serviceDhcp:
    enabled: false
  serviceDns:
    mixedService: true
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
      kube-vip.io/loadbalancerIPs: 192.168.50.20
  DNS1: 192.168.50.1
  DNS2: 192.168.1.1
  virtualHost: pi-hole.pi.home.notasecret.net
  serviceWeb:
    enabled: true
  extraEnvVars:
    FTLCONF_dns_listeningMode: 'all'
  whitelist:
    - mytv.clients.peacocktv.com
    - bff-ext.clients.peacocktv.com
    - imageservice.disco.peacocktv.com
    - play.ovp.peacocktv.com
  blacklist:
    - mt.ssai.peacocktv.com
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  

  